### PR TITLE
Update docker-image.yml

### PR DESCRIPTION
**Pull request by Helical-x**
Add linux/amd64,linux/arm64 platforms to docker build

### CODE REVIEW

**Comment by michaellperry** [comment]
My research seems to suggest this is not supported in GitHub Actions. @Helical-x, is there another way to accomplish what you're trying to achieve?

**Comment by Helical-x** [comment]
Hello @michaellperry, I have made some commits to the jinaga-postgres-fact-keystore repository according to Docker documentation https://docs.docker.com/build/ci/github-actions/multi-platform/
Could you execute the CI workflow in this pull?
https://github.com/jinaga/jinaga-postgres-fact-keystore/pull/3

**Comment by michaellperry** [comment]
The CI succeeded. I'll merge that PR. Please apply the same fix to this one.

**Comment by Helical-x** [comment]
> The CI succeeded. I'll merge that PR. Please apply the same fix to this one.

Done.

**Pull request merged**
